name: Yeni blog gönder
description: Yeni blog göndermek için blog bilgilerini gir ve issue aç.

title: "Yeni blog ekleme isteği"

body:
- type: input
  id: name
  attributes:
    label: Blog ismi
  validations:
    required: true

- type: input
  id: link
  attributes:
    label: Blog linki
  validations:
    required: true